runtime: java11
env: standard
runtime_config:
  jdk: openjdk11
env_variables:
  SPRING_PROFILES_ACTIVE: "production"
handlers:
  - url: /.*
    script: this field is required, but ignored
  - url: /static/blabber.css
    static_files: static/blabber.css
    upload: static/blabber.css
manual_scaling:
  instances: 1